services:
  api:
    image: ghcr.io/mateja-velickovic/stockhub-backend:${IMAGE_VERSION}
    build : null

  web:
    image: ghcr.io/mateja-velickovic/stockhub-frontend:${IMAGE_VERSION}
    build : null